# Generated by Django 6.0.4 on 2026-07-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(default='Remote', max_length=20),
        ),
    ]
