# Generated by Django 6.0.4 on 2026-07-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_posted_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
